#/usr/bin/zsh
if [ -d /etc/X11/xinit/xinitrc.d ] ; then
 for f in /etc/X11/xinit/xinitrc.d/?*.sh ; do
  [ -x "$f" ] && . "$f"
 done
 unset f
fi

#export GTK2_RC_FILES=/usr/share/themes/Adwaita-dark/gtk-2.0/gtkrc 
#export GTK_THEME=Adwaita:dark
#export QT_STYLE_OVERRIDE=adwaita-dark
export QT_QPA_PLATFORMTHEME=qt6ct
xfsettingsd &

numlockx
autocutsel -fork &
autocutsel -selection PRIMARY -fork &
dunst &
slstatus &
# picom -b
sxhkd &
switch_wallpapers.lisp &
xset s off -dpms # Disable DPMS and prevent screen from blanking
monitor-home &

xrandr --output DP-0 --primary --auto --dpi 144
xrandr --output HDMI-0 --right-of DP-0
xrdb -merge ~/.config/X11/xresources
xrdb -merge ~/.config/X11/xresources-theme

exec dwm
